### ISSUE TITLE
Help Wanted: Debug output across different models

### ISSUE THREAD

**Issue by qzed** [qzed/linux-surfacebook2-mshw0153#1]
## What is this all about?

I'm currently trying to write a driver for `MSHW0091`, which is central to a lot of functionality provided through the ACPI. A part of this is for the lid state. Now I hear you say "but who cares about the lid state if there's not even battery status?". Implementing the lid state is a lot easier than getting the battery information, and it seems like a good way to figure some things out, design-wise.

Now what does `MSHW0153` have to do with the lid state? To determine the lid state, the ACPI lid device queries `MSHW0091` for the current base status, i.e. if the base is attached or detached. It seems that those requests have to be handled by the driver of `MSHW0091`, thus this driver needs to know the status of the base. `MSHW0153` seems provide this information, among other things.

_Goal:_ `MSHW0153` provides three GPIO signals with corresponding interrupts related to the base of the device. Most likely, these signals correspond to (as indicated in the corresponding `_DSM` function):

- the base state (attached/detached),
- the dedicated GPU power state,
- the dedicated GPU presence.

I don't know, however, which signal corresponds to which state. I believe that with enough information, especially from device models without a discrete GPU, we can determine this.

## How can I help?

1. Clone this repository.
2. Build the module (`make`).
3. Load the module (`sudo insmod sb2_mshw0153.ko`).
4. Detach the device from the base, wait a bit and then re-attach it.
5. Repeat step 4 once or twice for good measure.
6. Unload the module (`sudo rmmod sb2_mshw0153.ko`).
7. Get the debug output (`dmesg | grep mshw0153 > output.log`)
8. Post the debug output here in combination with your device configuration (most importantly dedicated GPU, the rest should not really matter).

If you own a device with a dedicated GPU, I recommend unloading the `nouveau` module first (`sudo modprobe -r nouveau`), as this may cause some [issues](https://github.com/jakeday/linux-surface/issues/211) when detaching.

**Comment by mr-remington** [comment]
Here's the output (though seems a bit short). Done on a SB2 15' w/ 16GB. Detach/reattach done twice. 

[output.log](https://github.com/qzed/surfacebook2-linux-mshw0153/files/2377449/output.log)

Edit: ± uname -a
Linux sb2 4.18.7-surface-linux-surface #12 SMP Sun Sep 9 14:35:19 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux


[~/bin … surfacebook2-linux-mshw0153] master 12s 130 ± lspci -v
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
	Subsystem: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers
	Flags: bus master, fast devsel, latency 0
	Capabilities: <access denied>

00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: Microsoft Corporation UHD Graphics 620
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at d3000000 (64-bit, non-prefetchable) [size=16M]
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 4000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

00:04.0 Signal processing controller: Intel Corporation Skylake Processor Thermal Subsystem (rev 08)
	Subsystem: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem
	Flags: fast devsel, IRQ 16
	Memory at d4730000 (64-bit, non-prefetchable) [size=32K]
	Capabilities: <access denied>
	Kernel driver in use: proc_thermal
	Kernel modules: processor_thermal_device

00:05.0 Multimedia controller: Intel Corporation Skylake Imaging Unit (rev 01)
	Subsystem: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Imaging Unit
	Flags: fast devsel, IRQ 255
	Memory at d4000000 (64-bit, non-prefetchable) [disabled] [size=4M]
	Capabilities: <access denied>

00:13.0 Non-VGA unclassified device: Intel Corporation Sunrise Point-LP Integrated Sensor Hub (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP Integrated Sensor Hub
	Flags: bus master, fast devsel, latency 0, IRQ 20
	Memory at d4740000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel_ish_ipc
	Kernel modules: intel_ish_ipc

00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21) (prog-if 30 [XHCI])
	Subsystem: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller
	Flags: bus master, medium devsel, latency 0, IRQ 16
	Memory at d4700000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: xhci_hcd

00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP Thermal subsystem
	Flags: fast devsel, IRQ 18
	Memory at d4741000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel_pch_thermal
	Kernel modules: intel_pch_thermal

00:14.3 Multimedia controller: Intel Corporation Device 9d32 (rev 01)
	Subsystem: Intel Corporation Device 7270
	Flags: fast devsel, IRQ 16
	Memory at d4710000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel modules: ipu3_cio2

00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP Serial IO I2C Controller
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at d4742000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel-lpss
	Kernel modules: intel_lpss_pci

00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP Serial IO I2C Controller
	Flags: bus master, fast devsel, latency 0, IRQ 17
	Memory at d4743000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel-lpss
	Kernel modules: intel_lpss_pci

00:15.2 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #2 (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP Serial IO I2C Controller
	Flags: bus master, fast devsel, latency 0, IRQ 18
	Memory at d4744000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel-lpss
	Kernel modules: intel_lpss_pci

00:15.3 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #3 (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP Serial IO I2C Controller
	Flags: bus master, fast devsel, latency 0, IRQ 19
	Memory at d4745000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel-lpss
	Kernel modules: intel_lpss_pci

00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP CSME HECI
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at d4746000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: mei_me
	Kernel modules: mei_me

00:16.4 Communication controller: Intel Corporation Device 9d3e (rev 21)
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at d4747000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: mei_me
	Kernel modules: mei_me

00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
	Prefetchable memory behind bridge: 00000000d4400000-00000000d45fffff
	Capabilities: <access denied>

00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1) (prog-if 00 [Normal decode])
	Flags: fast devsel, IRQ 255
	Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
	I/O behind bridge: 00003000-00003fff
	Memory behind bridge: c0000000-d2ffffff
	Prefetchable memory behind bridge: 0000000090000000-00000000a1ffffff
	Capabilities: <access denied>

00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Bus: primary=00, secondary=03, subordinate=03, sec-latency=0
	Memory behind bridge: d4600000-d46fffff
	Capabilities: <access denied>

00:1e.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO UART Controller #0 (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP Serial IO UART Controller
	Flags: bus master, fast devsel, latency 0, IRQ 20
	Memory at d4748000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel-lpss
	Kernel modules: intel_lpss_pci

00:1f.0 ISA bridge: Intel Corporation Device 9d4e (rev 21)
	Subsystem: Intel Corporation Device 7270
	Flags: bus master, medium devsel, latency 0

00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP PMC
	Flags: fast devsel
	Memory at d473c000 (32-bit, non-prefetchable) [disabled] [size=16K]

00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21) (prog-if 80)
	Subsystem: Intel Corporation Sunrise Point-LP HD Audio
	Flags: bus master, fast devsel, latency 64, IRQ 16
	Memory at d4738000 (64-bit, non-prefetchable) [size=16K]
	Memory at d4720000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
	Subsystem: Intel Corporation Sunrise Point-LP SMBus
	Flags: medium devsel, IRQ 255
	Memory at d4749000 (64-bit, non-prefetchable) [disabled] [size=256]
	I/O ports at efa0 [disabled] [size=32]
	Kernel modules: i2c_i801

01:00.0 Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
	Subsystem: Device 0007:045e
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at d4500000 (64-bit, prefetchable) [size=1M]
	Memory at d4400000 (64-bit, prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel driver in use: mwifiex_pcie
	Kernel modules: mwifiex_pcie

02:00.0 3D controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev ff) (prog-if ff)
	!!! Unknown header type 7f
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

03:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961 (prog-if 02 [NVM Express])
	Subsystem: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961
	Flags: bus master, fast devsel, latency 0, IRQ 16, NUMA node 0
	Memory at d4600000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: nvme

**Comment by qzed** [comment]
@remingtonlang thanks!

**Comment by buoyancy99** [comment]
[output.log](https://github.com/qzed/surfacebook2-linux-mshw0153/files/2408285/output.log)
SurfaceBook 2 15in, 16G, 256G, GTX1060
Detached twice
Important: I did this when a SD card is plugged in base and. Will post another after removing SD card.

**Comment by buoyancy99** [comment]
[output.log](https://github.com/qzed/surfacebook2-linux-mshw0153/files/2408297/output.log)
Did this after previous post. Detach four times without SD card.
The log seems to contain overlapping contents with my previous trial with SD card.

**Comment by qzed** [comment]
@buoyancy99 thanks!

**Comment by qzed** [comment]
Okay, I think we've got enough logs from devices with a dGPU, but I still hope we can get one for a model without a dGPU too, that would help a lot.

The logs above are all consistent with my own findings. Based on the ACPI and the logs above, I think that the GPIO assignment is the following:

1. Base state
2. dGPU power
3. dGPU presence

With this the logs would indicate:

- On a disconnect, the dGPU power is cut first, before dGPU presence and base state are changed.
- On a connect, the base state is changed first, then dGPU presence and finally (and with a larger delay than between the first two) dGPU power.

From the DSDT, I can definitely say that dGPU power can/should only change to one after dGPU presence is set to one (connect). The above order is also the order they are referenced in the `_DSM` method in the DSDT, so I'm fairly certain that this is the correct designation. However a log from a model without the dGPU should only show changes in the base-state and thus give us a definitive answer on that.

**Comment by ghost** [comment]
I have the SB2 13" model with 8GB memory, no dedicated graphics.

uname -a: Linux Justin-SB2 4.18.7-surface-linux-surface #13 SMP Mon Sep 10 18:14:46 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

EDIT: Distro is elementary 0.4.1 if that means anything

[output.log](https://github.com/qzed/surfacebook2-linux-mshw0153/files/2416906/output.log)

Detached twice, did this while the base was plugged into wall power but otherwise nothing else was plugged in.

IDK if this is what you want but I hope it helps :)

**Comment by qzed** [comment]
@heartles Thanks! That actually helps a lot and confirms my suspicions! It looks like GPIO 1 is indeed the base state while 2 and 3 are associated with the dGPU.
