### ISSUE TITLE
Without DKMS

### ISSUE THREAD

**Issue by anthe** [qzed/linux-surfacebook2-mshw0153#4]
I'm on NixOS and I'd like to use sb2_shps but NixOS doesn't support DKMS. I tried repackaging this module as a kernel patch, but I'm no kernel developer, so my method was just pattern matching against the patches in linux-surface. While I did get the kernel to build with my patch, sysfs is still missing dgpu_power. So I'm wondering, are there any plans to get this module merged as a patch into jakeday/linux-surface?

**Comment by qzed** [comment]
Sorry I made you wait this long! I'll try to upload a kernel patch in the next couple of days.

With regards to merging this into jakeday/linus-surface, I think we have to discuss this with Jake a bit. The main issue I have right now with that is, that currently the driver does not support vgaswitcheroo or bumblebee yet and changes the default behavior (i.e. turns the dGPU off by default). This could break things for people that have set up their device without this module (but that will probably happen eventually even when this module supports bumblebee or vgaswitcheroo and is included then).

**Comment by qzed** [comment]
I've added a patch to include the module in the kernel in this repo, I'll prepare a PR for jakeday/linux-surface next.

**Comment by qzed** [comment]
PR is sent.

**Comment by anthe** [comment]
That worked! Many thanks!

**Comment by qzed** [comment]
Glad to know it works, thanks for the feedback!
